### ISSUE TITLE
部署的docker版本，本地用户登录方式，进入系统后没操作两下就会自动登出，跳回到登录页了，请问是什么原因

### ISSUE THREAD

**Issue by speeter** [Qihoo360/doraemon#77]
如题

**Comment by jayryu** [comment]
> 如题

最好按照wiki说明的步骤使用，不要加nginx等反向代理

**Comment by speeter** [comment]
> > 如题
> 
> 最好按照wiki说明的步骤使用，不要加nginx等反向代理

并没有加反向代理，直接访问的

**Comment by xphzzxpp** [comment]
> > > 如题
> > 
> > 
> > 最好按照wiki说明的步骤使用，不要加nginx等反向代理
> 
> 并没有加反向代理，直接访问的

我也是这样 请问你的HOOK URL如何配置的

**Comment by speeter** [comment]
> > > > 如题
> > > 
> > > 
> > > 最好按照wiki说明的步骤使用，不要加nginx等反向代理
> > 
> > 
> > 并没有加反向代理，直接访问的
> 
> 我也是这样 请问你的HOOK URL如何配置的

报警计划管理里可以配置，但是退出跟这个没关系啊，过一会儿就退出登录状态了

**Comment by speeter** [comment]
这里的doraemon的docker一直在重启，错误日志截图如下，烦请开发的协助定位一下。
<img width="765" alt="无标题" src="https://user-images.githubusercontent.com/9496937/97841923-bb64be00-1d21-11eb-952d-a50f9adf1573.png">

**Comment by speeter** [comment]
2020/11/01 19:07:31.209 [D] [server.go:2774]  |     172.18.0.5| 200 |   4.365672ms|   match| POST     /api/v1/alerts   r:/api/v1/alerts/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x969ab0]

goroutine 46 [running]:
github.com/Qihoo360/doraemon/cmd/alert-gateway/models.SendAlertsFor(0xc0001f7410, 0xc0001f7330, 0x1, 0xc0001f7a00)
	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/models/groups.go:81 +0x9a0
github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.Filter(0xc0001f7d98, 0xc0001f7d68, 0xc000199d40, 0xc0000bbca0)
	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:481 +0x1316
github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.InitTimer.func5.2(0xc00024c8e0, 0x13, 0xc000199d40)
	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:792 +0x518
created by github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.InitTimer.func5
	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:770 +0xd8
doraemon root:root@tcp(mysql:3306)/
2020/11/01 19:08:01.448 [D] [db.go:21]  Initialize database connection: ****:root@tcp(mysql:3306)/
2020/11/01 19:08:01.452 [I] [asm_amd64.s:1337]  http server Running on http://:8080
2020/11/01 19:08:46.205 [I] [controller.go:218]  [{2020-10-29 09:28:31.20117948 +0800 CST { cpu告警 1} 2020-10-29 09:28:46.20117948 +0800 CST map[resourceId:8e5c40a8-09d0-463c-82ff-d2e43e167511] 2020-11-01 19:08:46.20117948 +0800 CST 0001-01-01 00:00:00 +0000 UTC 2 2020-11-01 19:11:46.20117948 +0800 CST 15.23}]

**Comment by code871** [comment]
[root@TENCENT64 ~]# docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                               NAMES
009c2f63bf83        360cloud/doraemon-frontend:latest   "/usr/local/openre..."   5 months ago        Up 4 weeks          0.0.0.0:32000->80/tcp               docker-compose_doraemon-frontend_1
7486727795f9        360cloud/rule-engine:latest         "./ruleengine --ga..."   5 months ago        Up 4 weeks                                              docker-compose_ruleengine_1
08a4d494f772        360cloud/alert-gateway:latest       "./doraemon"             5 months ago        Up 4 seconds        0.0.0.0:8080->8080/tcp              docker-compose_doraemon-backend_1
cc4f52c594f2        mysql:5.7                           "docker-entrypoint..."   5 months ago        Up 4 weeks          0.0.0.0:3306->3306/tcp, 33060/tcp   docker-compose_mysql_1


一样的问题，每隔一段时间，后端容器就会每起来一分钟后不断重启，把doraemon库的alert表清空容器就不会再不断重启了，日志里没有啥有用的信息

**Comment by lycclsltt** [comment]
admin

**Comment by lycclsltt** [comment]
这tm是KPI项目吧？这么多人反馈也没个回复
